### ISSUE TITLE
Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

### ISSUE THREAD

**Issue by sissiautumn** [geodynamics/axisem#61]
Please help me figure out this problem. The axisem just calculated 49% and then segmentation faults appeared (every time).  Thanks in advance.

.......
  time step:  5500; t=  787.69 s ( 43.8%)
  time step:  5600; t=  802.01 s ( 44.6%)
  time step:  5700; t=  816.33 s ( 45.3%)
  time step:  5800; t=  830.65 s ( 46.1%)
  time step:  5900; t=  844.97 s ( 46.9%)
  time step:  6000; t=  859.29 s ( 47.7%)
  time step:  6100; t=  873.62 s ( 48.5%)
  time step:  6200; t=  887.94 s ( 49.3%)

Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:
#0  0x7f58064312da in ???
#1  0x7f5806430503 in ???
#2  0x7f580588ef1f in ???
#3  0x7f5805c49bd8 in ???
#4  0x563eaaad94e1 in c_wait_for_io
	at /home/dell/software/axisem-master/SOLVER/pthread.c:55
#5  0x563eaa775cf5 in __nc_routines_MOD_nc_rec_checkpoint
	at /home/dell/software/axisem-master/SOLVER/nc_routines.F90:599
#6  0x563eaa7bc448 in dump_stuff
	at /home/dell/software/axisem-master/SOLVER/time_evol_wave.F90:1144
#7  0x563eaa808070 in sf_time_loop_newmark
	at /home/dell/software/axisem-master/SOLVER/time_evol_wave.F90:498
#8  0x563eaa8081d6 in __time_evol_wave_MOD_time_loop
	at /home/dell/software/axisem-master/SOLVER/time_evol_wave.F90:238
#9  0x563eaa92d991 in axisem
	at /home/dell/software/axisem-master/SOLVER/main.f90:92
#10  0x563eaa92dbcc in main
	at /home/dell/software/axisem-master/SOLVER/main.f90:25
--------------------------------------------------------------------------
mpirun noticed that process rank 1 with PID 0 on node dell-Precision-7920-Tower exited on signal 11 (Segmentation fault).

**Comment by sissiautumn** [comment]
The error disappears after two weeks break, I didn't do anything :) 
If I change the length from 1800 s to 800 s, the IEEE_UNDERFLOW_FLAG problem shows up.
